### ISSUE TITLE
I would like to know more about how to configure and use "config" in detail.

### ISSUE THREAD

**Issue by PlumpMath** [Freax13/wol-mqtt#1]
Hello

 I'm particularly interested in understanding what "broker_ip" exactly means in the example YAML file. Please provide a detailed explanation. Also, I'd like to know the usage instructions for registering multiple computers as WOL targets in YAML and how to send a power-on signal to a selected computer.
 
 Thanks.

**Comment by Freax13** [comment]
Thanks for your interest! I created #2 to add some documentation. Please let me know if this clarifies your questions.
